version: '3'

services:
  strapi:
    container_name: strapi_cms_datafix
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
    restart: always

  db:
    container_name: mongo_db_datafix
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always


#  webserver:
#    image: nginx:alpine
#    container_name: react_webserver
#    ports:
#      - "8080:80"
#    volumes:
#      - ./ui/build:/usr/share/nginx/html:cached
#
#  node:
#    build:
#      context: .
#      dockerfile: ./ui/Dockerfile
#    container_name: react_node
#    image: react_node
#    working_dir: /var/www
#    ports:
#      - "35730:35729"
#    volumes:
#      - ./ui:/var/www:cached

