version: '3'

services:
  strapi-new:
    image: strapi/strapi
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    command: 'strapi start'

  react-prod:
    container_name: react-prod
    build:
      context: ./webapp
      dockerfile:
        Dockerfile
    ports:
      - "80:80"